sudo: required
language: python
services: docker

cache: pip

install:
  - pip install ansible docker ansible-lint
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/

script:
  - ansible --version
  - ansible-lint
  - tests/run.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
