---
- name: add distribution-specific variables
  include_vars: "../defaults/{{ ansible_distribution }}.yml"

- name: add backports repository
  apt_repository: repo='deb {{backports_uri}} {{backports_components}}' state=present update_cache=yes
