---
- name: Verify
  hosts: all
  become: True
  tasks:
    - name: List apt sources
      command: grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/
      register: aptsources
      changed_when: false

    - name: Check for backports repository
      assert:
        that: aptsources.stdout is search("backports")

    - name: Test sources pinning
      include_role:
        name: ansible-role-debian-backports
      vars:
        backports_priority_enabled: true

    - name: Check for pinning configuration
      stat:
        path: /etc/apt/preferences.d/001-ansible-role-debian-backports
        get_checksum: false
      register: pinconfig

    - name: Check if pinning was successful
      assert:
        that: pinconfig.stat.isreg
